{
	"type":"Live2D Expression",
	"fade_in":500,
	"fade_out":500,
	"params":[
		{"id":"PARAM_EYE_L","val":1},
		{"id":"PARAM_EYE_R","val":1},
		{"id":"PARAM_EYE_BALL_Y_2","val":-0.3},
		{"id":"PARAM_BROW_L_Y_1","val":-0.1},
		{"id":"PARAM_BROW_Y_1","val":-0.1},
		{"id":"PARAM_BROW_L_ANGLE_1","val":0.4},
		{"id":"PARAM_BROW_R_ANGLE_1","val":0.4},
		{"id":"PARAM_MOUTH_FORM_1","val":1},
		{"id":"PARAM_MOUTH_OPEN_Y","val":0.3}
	]
}