{
	"type":"Live2D Expression",
	"fade_in":500,
	"fade_out":500,
	"params":[
		{"id":"PARAM_EYE_L","val":0.5},
		{"id":"PARAM_EYE_R","val":0.5},
		{"id":"PARAM_EYE_BALL_Y_2","val":-0.6},
		{"id":"PARAM_TEAR","val":1},
		{"id":"PARAM_TEAR_1","val":1},
		{"id":"PARAM_BROW_L_FORM_1","val":-1},
		{"id":"PARAM_BROW_R_FORM_1","val":-1},
		{"id":"PARAM_ZHOUMEI","val":1},
		{"id":"PARAM_MOUTH_FORM_1","val":-2}
	]
}